#ifndef __COLORS_HPP__
#define __COLORS_HPP__

#define COLOR_BLACK 0xff000000
#define COLOR_WHITE 0xffffffff
#define COLOR_MENUBACKGROUND 0xffff2020
#define COLOR_MENUTEXT 0xffffffff
#define COLOR_SELECTEDLINE 0xff0000ff
#define COLOR_MOUSEOVERLINE 0xff40c0ff
#define COLOR_HEADERLINE 0xff404080
#define COLOR_HEADERTEXT 0xff80ffff
#define COLOR_PROMPTTEXT 0xffc0ffff

#endif //__COLORS_HPP__