#ifndef __CONSTANT_HPP__
#define __CONSTANT_HPP__

#define CHAR_HEIGHT 6
#define VK_NONE 0
#define VK_ESCAPE 27
#define VK_ENTER 13
#define VK_UP (72*256)
#define VK_PAGEUP (73*256)
#define VK_LEFT (75*256)
#define VK_RIGHT (77*256)
#define VK_LEFT_STRG (115*256)
#define VK_RIGHT_STRG (116*256)
#define VK_DOWN (80*256)
#define VK_PAGEDOWN (81*256)
#define VK_POS1 (71*256)
#define VK_END (79*256)
#define VK_F1 (59*256)
#define VK_F2 (60*256)
#define VK_F3 (61*256)
#define VK_F4 (62*256)
#define VK_F5 (63*256)
#define VK_F6 (64*256)
#define VK_F7 (65*256)
#define VK_F8 (66*256)
#define VK_F9 (67*256)
#define VK_F10 (68*256)
#define VK_TAB 9
#define VK_TAB_SHIFT (15*256)
#define VK_ENTF (83*256)
#define VK_INSERT (82*256)
#define VK_DELETE 8
#define VK_C_CTRL 3
#define VK_V_CTRL 22
#define VK_S_CTRL 19
#define VK_L_CTRL 12
#define VK_F_CTRL 6
#define VK_G_CTRL 7

#define EGA_COLOR_BLACK         0x00
#define EGA_COLOR_BLUE          0x01
#define EGA_COLOR_GREEN         0x02
#define EGA_COLOR_CYAN          0x03
#define EGA_COLOR_RED           0x04
#define EGA_COLOR_VIOLET        0x05
#define EGA_COLOR_BROWN         0x06
#define EGA_COLOR_GREY_LIGHT    0x07
#define EGA_COLOR_GREY_DARK     0x08
#define EGA_COLOR_BLUE_LIGHT    0x09
#define EGA_COLOR_GREEN_LIGHT   0x0a
#define EGA_COLOR_CYAN_LIGHT    0x0b
#define EGA_COLOR_RED_LIGHT     0x0c
#define EGA_COLOR_VIOLET_LIGHT  0x0d
#define EGA_COLOR_YELLOW        0x0e
#define EGA_COLOR_WHITE         0x0f

#define DISPLAYOUTLINE_DURATION 32

#endif //__CONSTANT_HPP__