#ifndef __TYPES_HPP__
#define __TYPES_HPP__

#define NULL 0
#define NIL "<NIL>"

//typedef signed long int int64_t; // 64 bit support is broken in WatcomC. this is not 64 bit
//typedef unsigned long int uint64_t; // 64 bit support is broken in WatcomC. this is not 64 bit
typedef signed int int32_t;
typedef unsigned int uint32_t;
typedef signed short int16_t;
typedef unsigned short uint16_t;
typedef signed char int8_t;
typedef unsigned char uint8_t;

#endif //__TYPES_HPP__